name: Super Linter

on: [push, pull_request]

jobs:
  super-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter/slim@v6  # ✅ Use 'slim' version for smaller image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true

